site_name: CaribData Open Data — Caribbean
theme:
  name: material
nav:
  - Home: index.md
#  - Datasets: datasets.md
  - Downloads: downloads.md
  - Messy Data: messy.md
#  - How To: howto.md
repo_url: https://github.com/CaribData/open-data-caribbean
