name: CaribData Open Data — Build & Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # Mondays 06:00 UTC (optional)
  push:
    branches: [ "main" ]  # build on normal pushes (no release)
    tags:
      - "v*"              # e.g., v2025.08.22
      - "od-*"            # e.g., od-v2025-08-22 or od-2025.08.22

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build datasets (retry up to 3x)
        env:
          CARIBDATA_HTTP_TIMEOUT: "90"
          CARIBDATA_HTTP_RETRIES: "6"
          CARIBDATA_HTTP_BACKOFF: "0.8"
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i ..."
            if python scripts/build_wb_fao.py; then
              echo "Build succeeded on attempt $i"
              break
            fi
            if [ "$i" -eq 3 ]; then
              echo "Build failed after 3 attempts"
              exit 1
            fi
            sleep $((i*30))
          done

      - name: Data quality report
        run: python scripts/generate_quality_report.py || true

      - name: Upload build artifact (for release job)
        uses: actions/upload-artifact@v4
        with:
          name: data-package
          path: |
            data/
            catalog.yml

  release:
    needs: build
    # Only when it was a tag push
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/od-')
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: data-package
          path: data-package

      - name: Make distributable zip + checksum
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF#refs/tags/}"
          mkdir -p dist
          # One zip containing ALL generated data
          ZIP="open-data-caribbean_${TAG}.zip"
          (cd data-package && zip -r "../dist/${ZIP}" data catalog.yml >/dev/null)
          shasum -a 256 "dist/${ZIP}" > "dist/${ZIP}.sha256"
          echo "zip=dist/${ZIP}" >> "$GITHUB_OUTPUT"
          echo "sha=dist/${ZIP}.sha256" >> "$GITHUB_OUTPUT"
          echo "Created $(ls -lh dist/${ZIP})"

      - name: Create/Update GitHub Release (attach single zip)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.sha }}
          body: |
            CaribData Open Data — automated build.
            Asset:
            - ${{ steps.pack.outputs.zip }} (SHA256 in .sha256)
            Contents include:
            - data/world_bank/*, data/faostat_fbs/*, _dictionary/_manifest/_freshness/_quality_report
