name: CaribData Open Data - Build and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"  # Mondays 06:00 UTC
  push:
    paths:
      - "scripts/**"
      - "catalog.yml"
      - ".github/workflows/build-release.yml"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pinned by requirements.txt)
        run: pip install -r requirements.txt

      - name: Build datasets
        run: python scripts/build_wb_fwo.py

      - name: Freshness stamp preview
        run: cat data/_freshness.json || true

      - name: Data quality report
        run: python scripts/generate_quality_report.py

      - name: Validate CSVs (frictionless) - non-fatal
        continue-on-error: true
        run: |
          frictionless validate data --type package || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-package
          path: |
            data/
            catalog.yml

  # Optional release on tags (keep your current tagging strategy)
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: data-package
          path: data-package
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            data-package/**/*
          body: |
            Automated data build. Includes:
            - World Bank per-country CSVs + _dictionary.csv + _manifest.json
            - FAOSTAT FBS CSVs + _manifest.json
            - Freshness stamp + quality report
