name: CaribData Open Data — Build & Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # Mondays 06:00 UTC
  push:
    branches: [ "main" ]  # build on normal pushes
    tags:
      - "v*"              # ALSO build+release when a tag like v2025.08.22 is pushed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build datasets (retry up to 3x)
        env:
          CARIBDATA_HTTP_TIMEOUT: "90"
          CARIBDATA_HTTP_RETRIES: "6"
          CARIBDATA_HTTP_BACKOFF: "0.8"
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i ..."
            if python scripts/build_wb_fao.py; then
              echo "Build succeeded on attempt $i"
              break
            fi
            if [ "$i" -eq 3 ]; then
              echo "Build failed after 3 attempts"
              exit 1
            fi
            sleep $((i*30))
          done

      - name: Freshness stamp preview
        run: cat data/_freshness.json || true

      - name: Data quality report
        run: python scripts/ggenerate_quality_report.py || python scripts/generate_quality_report.py

      - name: Validate CSVs (non-fatal)
        continue-on-error: true
        run: |
          frictionless validate data/world_bank/**/*.csv || true
          frictionless validate data/faostat_fbs/*.csv || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-package
          path: |
            data/
            catalog.yml

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')   # only when tag like v2025.08.22
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: data-package
          path: data-package

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            data-package/**/*
          body: |
            CaribData Open Data — automated build.
            Includes:
            - World Bank per-country CSVs + _dictionary.csv + _manifest.json
            - FAOSTAT FBS CSVs + _manifest.json
            - Freshness stamp + quality report
