name: Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
      - "scripts/gen_downloads.py"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CaribData Open Data — Build & Release"
      - "CaribData Messy Data — Fetch & Bundle"
      - "CaribData Messy Data — Release"
    types: [completed]

permissions:
  contents: write
  actions: read

concurrency:
  group: docs-site
  cancel-in-progress: true

jobs:
  build-deploy:
    if: github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs (minimal)
        run: |
          set -eux
          pip install mkdocs mkdocs-material
          mkdocs --version

      # Read-only gh-pages so we can list /data/<TAG>/...
      - name: Checkout gh-pages (read-only)
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: ghp
          fetch-depth: 0

      - name: Ensure gh-pages workspace exists
        run: |
          set -eux
          mkdir -p ghp ghp/data
          ls -la ghp || true
          ls -la ghp/data || true
          [ -f ghp/data/latest.json ] && { echo "latest.json:"; cat ghp/data/latest.json; } || echo "(no latest.json)"

      - name: Generate Downloads page (Python)
        run: |
          set -eux
          python scripts/gen_downloads.py
          head -n 80 docs/downloads.md || true

      - name: Build site
        run: |
          set -eux
          mkdocs build --strict

      - name: Deploy to GitHub Pages (preserve existing data/)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
