name: Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
  workflow_dispatch:
  workflow_run:
    workflows: ["CaribData Open Data — Build & Release"]
    types: [completed]

permissions:
  contents: write
  actions: read

concurrency:
  group: docs-site
  cancel-in-progress: true

jobs:
  build-deploy:
    if: github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs + deps
        run: |
          pip install -r requirements.txt
          mkdocs --version

      - name: Show mkdocs.yml (debug)
        run: |
          echo "----- mkdocs.yml -----"
          cat mkdocs.yml
          echo "----------------------"

      - name: Build site
        run: mkdocs build --strict

      - name: List built site (debug)
        run: |
          echo "Built files in ./site:"
          find site -maxdepth 2 -type f | head -n 50
          echo "Grepping title from homepage:"
          grep -i "<title>" site/index.html || true

      - name: Deploy to GitHub Pages (force clean)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
