name: CaribData Messy Data — Release

on:
  push:
    tags:
      - "md-v*"   # e.g., md-v2025.08.22
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build messy bundle
        env:
          CARIBDATA_HTTP_TIMEOUT: "120"
          CARIBDATA_HTTP_RETRIES: "6"
          CARIBDATA_HTTP_BACKOFF: "0.8"
        run: python scripts/fetch_messy.py

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            data/messy/belize-messy-bundle.zip
            data/messy/_manifest.json
            data/messy/_report.json
            data/messy/_dataset_card.md
          body: |
            CaribData Messy Data (Belize) — automated bundle.
            Purpose: stress-test ingest/clean pipelines.
            See _manifest.json and _report.json for details.
